trigger: none



pr: none




stages:

- stage: Validate

  jobs:

  - job: Build

    pool:

      vmImage: 'ubuntu-latest'

      variables: 

        ErrorText: ''

    steps:


      - task: CopyFiles@2

        displayName: 'Create project folder'

        inputs:

          SourceFolder: '$(System.DefaultWorkingDirectory)/logic-app-v2/blob-connection'

          Contents: |

              *.json

          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - script: dir
        workingDirectory: $(Build.ArtifactStagingDirectory)
        displayName: List contents of a folder


      - task: PublishPipelineArtifact@1

        displayName: 'Publish project artifact'

        inputs:
          targetPath:: '$(Build.ArtifactStagingDirectory)'

          artifact: 'logic_createincident'

          publishLocation: 'pipeline'



- stage: Deploy

  displayName: 'Deployment'

  jobs:

  - job: deploy_logicapp_resources

    displayName: Deploy Logic App

    pool:

      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'logic_createincident'
        path: '$(Build.ArtifactStagingDirectory)'
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Pipeline.Workspace)
    - bash: echo $(Pipeline.Workspace)/$(Build.BuildId)
    - script: dir
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: List contents of a folder
    - task: AzureResourceGroupDeployment@2

      displayName: 'Deploy Logic App'

      inputs:

        azureSubscription: 'huidong'
        ConnectedServiceName: 'huidong'

        resourceGroupName: 'huidong'

        location: 'southeastasia'

        csmFile: '$(Build.ArtifactStagingDirectory)/a/template.json'

        csmParametersFile: '$(Build.ArtifactStagingDirectory)/a/parameters.json'

  
        deploymentMode: 'Incremental'