trigger: none



pr: none




stages:

- stage: Validate

  jobs:

  - job: Build

    pool:

      vmImage: 'ubuntu-latest'

      variables: 

        ErrorText: ''

    steps:

      # - task: AzureResourceGroupDeployment@2

      #   displayName: 'Validate Logic App'

      #   inputs:

      #     azureSubscription: 'huidong'

      #     resourceGroupName: 'huidong'

      #     location: 'japaneast'

      #     csmFile: '/../template/template.json'

      #     csmParametersFile: '/../template/parameters.json'
      #     deploymentMode: Validation



      - task: CopyFiles@2

        displayName: 'Create project folder'

        inputs:

          SourceFolder: '$(System.DefaultWorkingDirectory)/logic-app-v1/template'

          Contents: |

              *.json

          TargetFolder: '$(Build.ArtifactStagingDirectory)'


      - task: PublishBuildArtifacts@1
        displayName:  Publish build artifacts
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'logic_createincident'

      # - task: PublishPipelineArtifact@1

      #   displayName: 'Publish project artifact'

      #   inputs:
      #     targetPath:: '$(Build.ArtifactStagingDirectory)'

      #     artifact: 'logic_createincident'

      #     # publishLocation: 'pipeline'



- stage: Deploy

  displayName: 'Deployment'

  jobs:

  - job: deploy_logicapp_resources

    displayName: Deploy Logic App

    pool:

      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'logic_createincident'
        path: '$(Build.ArtifactStagingDirectory)'
    - task: AzureResourceGroupDeployment@2

      displayName: 'Deploy Logic App'

      inputs:

        azureSubscription: 'huidong'
        ConnectedServiceName: 'huidong'

        resourceGroupName: 'huidong'

        location: 'japaneast'

        csmFile: '$(Agent.BuildDirectory)/logic_createincident/template.json'

        csmParametersFile: '$(Agent.BuildDirectory)/logic_createincident/parameters.json'

        # overrideParameters: '-inc_password tuydwoqfn'

        deploymentMode: 'Incremental'